### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by Shahelion** [MikeLydeamore/IlluminatedBows#15]
http://hastebin.com/ejefafusol.coffee

**Comment by tterrag1098** [comment]
This is not Illuminated Bows' fault, it just passes through our code as we wrap the wand renderer. You seem to have invalid NBT data on the wand item (did you transfer your inventory from an old world?), and would crash even without Illuminated Bows installed (try it!).

**Comment by Shahelion** [comment]
I was in a creative world with a wand, then I went to make a new survival world and this happened. No idea why.

**Comment by tterrag1098** [comment]
Well either way it's not our problem, it's some kind of weird bug with TC.

**Comment by Shahelion** [comment]
But it only happens with this mod installed. Which is odd because it wasn't even a focus from this mod on the wand.

**Comment by tterrag1098** [comment]
There's no way that's true. It crashes inside Thaumcraft code when it tries to get the wand focus.

**Comment by Shahelion** [comment]
Original crash report timed out and deleted, closing issue.
